{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fab482fe-7a24-400e-9df1-91007288a753",
   "metadata": {},
   "outputs": [],
   "source": [
    "from fastapi import FastAPI, Request\n",
    "from pydantic import BaseModel\n",
    "import joblib\n",
    "import pandas as pd\n",
    "\n",
    "# 1. Crear instancia de FastAPI\n",
    "app = FastAPI()\n",
    "\n",
    "# 2. Cargar el modelo entrenado\n",
    "model = joblib.load(\"modelo_protocolo.pkl\")\n",
    "\n",
    "# 3. Definir el esquema de entrada\n",
    "class Producto(BaseModel):\n",
    "    Embalaje: int\n",
    "    Ancho: float\n",
    "    Largo: float\n",
    "    Alto: float\n",
    "    Peso_kg: float\n",
    "    Procedencia: int\n",
    "    Manipulacion: int\n",
    "    Temperatura: int\n",
    "\n",
    "# 4. Ruta raíz para verificar que la API funciona\n",
    "@app.get(\"/\")\n",
    "def read_root():\n",
    "    return {\"mensaje\": \"API de clasificación de protocolo activa\"}\n",
    "\n",
    "# 5. Ruta de inferencia\n",
    "@app.post(\"/predecir\")\n",
    "def predecir_protocolo(producto: Producto):\n",
    "    # Convertir entrada en DataFrame\n",
    "    entrada = pd.DataFrame([{\n",
    "        \"Embalaje\": producto.Embalaje,\n",
    "        \"Ancho\": producto.Ancho,\n",
    "        \"Largo\": producto.Largo,\n",
    "        \"Alto\": producto.Alto,\n",
    "        \"Peso (kg)\": producto.Peso_kg,\n",
    "        \"Procedencia\": producto.Procedencia,\n",
    "        \"Manipulacion\": producto.Manipulacion,\n",
    "        \"Temperatura\": producto.Temperatura\n",
    "    }])\n",
    "    \n",
    "    # Realizar predicción\n",
    "    prediccion = model.predict(entrada)[0]\n",
    "    \n",
    "    # Traducir resultado si es necesario\n",
    "    protocolo = \"Protocolo_1\" if prediccion == 0 else \"Protocolo_2\"\n",
    "    \n",
    "    return {\n",
    "        \"protocolo_predicho\": protocolo,\n",
    "        \"datos_entrada\": entrada.to_dict(orient=\"records\")[0]\n",
    "    }"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7d6b26c3-ebf7-4c7e-94a7-ae1dabaea3a4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Viaje 1: Productos [1, 5, 3], Ruta: [(0, 0), (0, 4), (5, 1)] → (0,0)\n",
      "\n",
      "Viaje 2: Productos [2, 4, 6], Ruta: [(1, 0), (5, 0), (1, 4)] → (0,0)\n"
     ]
    }
   ],
   "source": [
    "# Inciso 5\n",
    "# programa que determina la ruta óptima que debe tomar el vehículo para distribuir los productos por la planta industrial\n",
    "\n",
    "\n",
    "import numpy as np\n",
    "import itertools\n",
    "\n",
    "# 1. Coordenadas de productos extraídas manualmente de la imagen\n",
    "productos = [\n",
    "    {'id': 1, 'x': 0, 'y': 0, 'protocolo': 'Protocolo_1'},  # Amarillo\n",
    "    {'id': 2, 'x': 1, 'y': 0, 'protocolo': 'Protocolo_2'},  # Naranja\n",
    "    {'id': 3, 'x': 5, 'y': 1, 'protocolo': 'Protocolo_1'},  # Verde\n",
    "    {'id': 4, 'x': 5, 'y': 0, 'protocolo': 'Protocolo_2'},  # Rojo oscuro\n",
    "    {'id': 5, 'x': 0, 'y': 4, 'protocolo': 'Protocolo_1'},  # Rojo\n",
    "    {'id': 6, 'x': 1, 'y': 4, 'protocolo': 'Protocolo_2'}   # Verde oscuro\n",
    "]\n",
    "\n",
    "# 2. Función de distancia Manhattan\n",
    "def distancia(p1, p2):\n",
    "    return abs(p1['x'] - p2['x']) + abs(p1['y'] - p2['y'])\n",
    "\n",
    "# 3. Ruta óptima para un lote de productos\n",
    "def mejor_ruta(lote):\n",
    "    rutas = itertools.permutations(lote)\n",
    "    origen = {'x': 0, 'y': 0}  # Almacén\n",
    "    return min(rutas, key=lambda r: sum(distancia(origen if i == 0 else r[i-1], r[i]) for i in range(len(r))))\n",
    "\n",
    "# 4. Planificador de viajes\n",
    "def planificar_rutas(productos):\n",
    "    viajes = []\n",
    "    pendientes = sorted(productos, key=lambda p: p['protocolo'])  # Prioriza Protocolo_1\n",
    "    while pendientes:\n",
    "        lote = []\n",
    "        destinos = set()\n",
    "        for p in pendientes:\n",
    "            coord = (p['x'], p['y'])\n",
    "            if coord not in destinos:\n",
    "                lote.append(p)\n",
    "                destinos.add(coord)\n",
    "            if len(lote) == 3:\n",
    "                break\n",
    "        for p in lote:\n",
    "            pendientes.remove(p)\n",
    "        ruta = mejor_ruta(lote)\n",
    "        viajes.append({\n",
    "            'productos': [p['id'] for p in ruta],\n",
    "            'ruta': [(p['x'], p['y']) for p in ruta]\n",
    "        })\n",
    "    return viajes\n",
    "\n",
    "# 5. Ejecutar\n",
    "viajes = planificar_rutas(productos)\n",
    "for i, v in enumerate(viajes):\n",
    "    print(f\"\\nViaje {i+1}: Productos {v['productos']}, Ruta: {v['ruta']} → (0,0)\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "081e7329-2e8c-469c-8fae-751fa95b0409",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "anaconda-panel-2023.05-py310",
   "language": "python",
   "name": "conda-env-anaconda-panel-2023.05-py310-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
